version: '3.9'

services:

  rancher:
    image: rancher/rancher:latest
    privileged: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - rancher:/var/lib/rancher
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

volumes:
  rancher:
